### ISSUE TITLE
Support resizing PyNvim window

### ISSUE THREAD

**Issue by viccuad** [neovim/python-gui#16]
I haven't been able to resize `pynvim` window, with neovim 0.1.2, python-client 0.1.2 and python-gui 0.1.1 (I haven't tried with neovim's master and python-client >= 0.1.3).

**Comment by bfredl** [comment]
looks like division issue. Please try master (which needs latest python-client)

**Comment by zsedem** [comment]
It does fixed for me using the master for this repo and up-to-date arch linux packages for dependencies
