### ISSUE TITLE
Unable to install using pip in windows

### ISSUE THREAD

**Issue by Rafi993** [neovim/python-gui#22]
when I tried to install using pip in windows 7 X64 it throws me the following error

`ERROR: Could not find pkg-config: Please check your PATH environment variable.`

**Comment by Tset-Noitamotua** [comment]
same here (with Python 2.7):

``` cmd
(VIM) my_user@host C:\Users\my_user
$ pip install neovim-gui
Collecting neovim-gui
  Downloading neovim_gui-0.1.3.tar.gz (65kB)
    100% |################################| 71kB 1.0MB/s
Collecting neovim>=0.1.3 (from neovim-gui)
  Downloading neovim-0.1.9.tar.gz
Collecting click>=3.0 (from neovim-gui)
Collecting pygobject (from neovim-gui)
  Downloading pygobject-2.28.3.tar.bz2 (889kB)
    100% |################################| 890kB 752kB/s
    Complete output from command python setup.py egg_info:
    ERROR: Could not find pkg-config: Please check your PATH environment variable.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\my_user\appdata\local\temp\pip-build-drrixy\pygobject\
```

Some missing dependencies? Which?

Cheers
Tset

**Comment by justinmk** [comment]
pkg-config is a program needed by the setup. Not sure how one would go about getting that on windows. I'd be really surprised if this project worked at all on Windows.

Closing this since so far there is no mention of a problem that we can control. (Install pkg-config!)

**Comment by Tset-Noitamotua** [comment]
I didn´t try it but if some one wants to try - here is [how to install pkg config in windows](http://stackoverflow.com/questions/1710922/how-to-install-pkg-config-in-windows).

**Comment by Tset-Noitamotua** [comment]
just for completeness ... 

with Python 3.5.2 there is a different error:

``` cmd
$ pip install neovim-gui
Collecting neovim-gui
  Using cached neovim_gui-0.1.3.tar.gz
Requirement already satisfied (use --upgrade to upgrade): neovim>=0.1.3 in c:\users\my_user\envs\vim\lib\site-packages (from neovim-gui)
Collecting click>=3.0 (from neovim-gui)
Collecting pygobject (from neovim-gui)
  Using cached pygobject-2.28.3.tar.bz2
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\my_user\AppData\Local\Temp\pip-build-0kxcyw4z\pygobject\setup.py", line 272
        raise SystemExit, 'ERROR: Nothing to do, gio could not be found and is essential.'
                        ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\my_user\AppData\Local\Temp\pip-build-0kxcyw4z\pygobject\
```

**Comment by bfredl** [comment]
That seems to be an error in pygobject package on windows, it uses py2-only syntax (but if I remember correctly pygobject must be installed through a `.whl` on windows and system package manager on Linux, never by building source distro in pip, so this is probably an error of showing the error, still one would expect `setup.py` to be legal python3...)
