### ISSUE TITLE
pynvim crashes on startup

### ISSUE THREAD

**Issue by jpleau** [neovim/python-gui#5]
Hi.

Tested on both Debian unstable and stable, on i3wm and openbox. I have neovim installed (tried both 0.1.2 releases and current HEAD: 8991b4b095c9b4817eb88e003201292e11e05fae)

I have installed neovim and neovim-gui through pip, also tried installing them both from their git master branches. I get the same error on both python2 and python3.

Here's the error(s) I'm getting: https://gist.github.com/jpleau/f76eee22fd1cbdd64fe1

Any ideas what the problem might be ? Deleteing my vim/nvim config files also do not solve this issue.

Thanks

**Comment by viccuad** [comment]
It works here on Debian Testing, from the package I'm doing at (warning, uncomplete package)
https://anonscm.debian.org/cgit/python-modules/packages/python-neovim-gui.git

Have you installed the needed dependencies?
`python-gi  python-click  python3-gi python3-click`

**Comment by jpleau** [comment]
(as discussed on irc)

I do have all the dependencies. Have also tried on GNOME, I am getting the same error

**Comment by Shougo** [comment]
I cannot reproduce the error in ManjaroLinux/Ubuntu 14.04.

**Comment by jpleau** [comment]
Found it: on debian, you also need to install python3-gi-cairo, as well as gir1.2-gtk-3.0

**Comment by viccuad** [comment]
I also needed to install python3-cairo.

So, to recapitulate, if you want to use the python3 version of python-gui on Debian/Ubuntu, either install Gnome DE or `python3-gi python3-click python3-click python3-gi-cairo python3-cairo gir1.2-gtk-3.0`
